name: TruffleHog Scan

on:
  push:
    branches: [ main ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          extra_args: --only-verified --fail
